# Generated by Django 6.0.1 on 2026-02-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('display_title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=32)),
                ('topic', models.CharField(max_length=128)),
                ('difficulty', models.PositiveSmallIntegerField(default=2)),
                ('statement_template', models.TextField()),
                ('generator_key', models.CharField(max_length=64)),
                ('params_schema', models.JSONField(blank=True, default=dict)),
                ('hint', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('informatics', 'Информатика'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('russian', 'Русский'), ('english', 'Английский'), ('social', 'Обществознание'), ('history', 'История'), ('geo', 'География')], max_length=32, verbose_name='Предмет')),
                ('topic', models.CharField(max_length=120, verbose_name='Тема')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='Сложность (1-10)')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('hint', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_generated', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('gen_params', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_problems', to='problems.problemtemplate')),
            ],
        ),
    ]
