# Generated by Django 6.0.1 on 2026-02-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('active', 'Идёт'), ('finished', 'Завершён'), ('cancelled', 'Отменён'), ('technical', 'Техническая ошибка')], db_index=True, default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('allow_resubmit', models.BooleanField(default=True)),
                ('duration_sec', models.PositiveIntegerField(default=90)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('p1_win', 'Победа игрока 1'), ('p2_win', 'Победа игрока 2'), ('draw', 'Ничья'), ('cancelled', 'Отменён'), ('technical', 'Техническая ошибка')], max_length=20, null=True)),
                ('p1_state', models.CharField(choices=[('idle', 'Не отвечал'), ('wrong', 'Неверно'), ('correct', 'Верно')], default='idle', max_length=10)),
                ('p2_state', models.CharField(choices=[('idle', 'Не отвечал'), ('wrong', 'Неверно'), ('correct', 'Верно')], default='idle', max_length=10)),
                ('p1_score', models.PositiveSmallIntegerField(default=0)),
                ('p2_score', models.PositiveSmallIntegerField(default=0)),
                ('p1_last_answer', models.TextField(blank=True, default='')),
                ('p2_last_answer', models.TextField(blank=True, default='')),
                ('p1_last_submit_at', models.DateTimeField(blank=True, null=True)),
                ('p2_last_submit_at', models.DateTimeField(blank=True, null=True)),
                ('p1_rating_before', models.IntegerField(blank=True, null=True)),
                ('p2_rating_before', models.IntegerField(blank=True, null=True)),
                ('p1_rating_after', models.IntegerField(blank=True, null=True)),
                ('p2_rating_after', models.IntegerField(blank=True, null=True)),
                ('p1_connected', models.BooleanField(default=False)),
                ('p2_connected', models.BooleanField(default=False)),
                ('p1_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('p2_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_matches_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvp_matches_as_p2', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvp_matches', to='problems.problem')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvp_wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
